### ISSUE TITLE
Please update aws sdk v2 version. schema-registry-serde:1.1.17 conflicts with latest aws-sdk libs.

### ISSUE THREAD

**Issue by blestka** [awslabs/aws-glue-schema-registry#319]
Please update aws sdk v2 to a newer version.

When using schema-registry-serde:1.1.17 together with aws sdk v2 libraries, which versions are 2.21.7 and higher, got exceptions due to breaking changes introduced in latter aws sdk v2 versions. 

Have to explicitly exclude transient dependencies from schema-registry-serde, e.g. sts library. Reason is the error below:

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.kafka.common.serialization.Deserializer]: Factory method 'glueDeserializer' threw exception with message: software/amazon/awssdk/protocols/query/interceptor/QueryParametersToBodyInterceptor
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)

Caused by: java.lang.NoClassDefFoundError: software/amazon/awssdk/protocols/query/interceptor/QueryParametersToBodyInterceptor
	at software.amazon.awssdk.services.sts.DefaultStsBaseClientBuilder.finalizeServiceConfiguration(DefaultStsBaseClientBuilder.java:68)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:160)

**Comment by YangSan0622** [comment]
We are working on releasing 1.1.18 right now, it should be done shortly and we will update aws sdk v2 version to latest in this release.

**Comment by YangSan0622** [comment]
We have released v1.1.18 and the AWS SDK v2 version is updated! Thank you!
